### ISSUE TITLE
Adding dataset Paris Bible Project

### ISSUE THREAD

**Issue by parisbible** [HTR-United/htr-united#101]
```yaml
schema: https://htr-united.github.io/schema/2022-04-15/schema.json
title: Paris Bible Project (PBP)
url: https://github.com/parisbible
authors:
  - name: Estelle
    surname: Guéville
    orcid: 0000-0003-2603-1051
    roles:
      - transcriber
      - aligner
      - project-manager
      - quality-control
  - name: David
    surname: Wrisley
    orcid: 0000-0002-0355-1487
    roles:
      - transcriber
      - aligner
      - project-manager
      - quality-control
  - name: Niccolò Acram
    surname: Cappelletto
    roles:
      - transcriber
      - aligner
      - quality-control
institutions: []
description: >-
  The Paris Bible Project aims to understand the production and diffusion of
  medieval Latin Bibles in Europe. The dataset includes ground truth from Paris
  Bibles produced in the 13th and 14th centuries. We also provide the most
  recent version of our list of Paris Bible manuscripts found in the world along
  with information about them.
project-website: https://parisbible.github.io/
language:
  - lat
production-software: Transkribus
script:
  - iso: Latn
  - iso: Goth
script-type: only-manuscript
time:
  notBefore: '1200'
  notAfter: '1399'
hands:
  count: more-than-10
  precision: estimated
license:
  - name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
format: Alto-XML
volume:
  - metric: lines
    count: 10000
transcription-guidelines: 'See: https://parisbible.github.io/guidelines/'
```
