### ISSUE TITLE
Adding dataset NaN

### ISSUE THREAD

**Issue by soniasol** [HTR-United/htr-united#109]
Hello ! [Complete your message here]

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2022-04-15/schema.json
title: Test
url: https://github.com/soniasol/Test
authors:
  - name: Sonia
    surname: Solfrini
    roles:
      - transcriber
institutions: []
description: Test to learn about Github
language:
  - fra
production-software: eScriptorium + Kraken
script:
  - iso: Latn
script-type: mainly-typed
time:
  notBefore: '1500'
  notAfter: '1599'
hands:
  count: '1'
  precision: exact
license:
  - name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
format: Alto-XML
```
