### ISSUE TITLE
Adding dataset NaN

### ISSUE THREAD

**Issue by jschaefer738b** [HTR-United/htr-united#119]
Hello !

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2022-04-15/schema.json
title: Joseph Hooker HTR
url: https://github.com/jschaefer738b/JosephHookerHTR.git
authors:
  - name: John
    surname: Schaefer
    orcid: 0009-0006-5751-9323
    roles:
      - transcriber
      - project-manager
      - quality-control
      - support
  - name: Kiri
    surname: Ross-Jones
    roles:
      - support
  - name: Alexis
    surname: Litvine
    roles:
      - support
institutions:
  - name: Royal Botanic Gardens, Kew
  - name: University of Cambridge
description: >-
  XML transcriptions and JPEG images exported from Transkribus as ground truth
  for an eScriptorium-Kraken HTR model (CER 11-12%) trained on the correspondence of Joseph
  Dalton Hooker (1817-1911), primarily letters to William Turner Thiselton-Dyer
  (1843-1928) during the late-19th/early-20th century. Many transcriptions in
  this dataset were generated by a small team of anonymous volunteers as part of
  the Joseph Hooker Correspondence Project based at Kew Gardens. All images in
  this dataset are reproduced with the kind permission of the Board of Trustees
  of the Royal Botanic Gardens Kew (© RBG, Kew). Contact archives@kew.org for
  more information.


  HTR Model: Schaefer, John, & Litvine, Alexis. (2023). Joseph Hooker HTR Model.
  Zenodo. https://doi.org/10.5281/zenodo.8038689
project-name: Joseph Hooker Correspondence Project
project-website: >-
  https://www.kew.org/science/our-science/projects/joseph-hooker-correspondence-project
language: eng
production-software: Transkribus
script:
  - iso: Latn
script-type: only-manuscript
time:
  notBefore: '1850'
  notAfter: '1911'
hands:
  count: '1'
  precision: estimated
license:
  - name: CC-BY-SA 4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
format: Page-XML
volume:
  - metric: lines
    count: 7100
  - metric: files
    count: 337
  - metric: pages
    count: 337
transcription-guidelines: >-
  All horizontal lines in Hooker's hand were transcribed as originally written.
  Most typescript and vertical lines in the margins were not included.
```
