### ISSUE TITLE
Adding dataset htromance italian

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#126]
Hello ! You're awesome! <3

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
title: htromance ita
url: https://github.com/HTRomance-Project/medieval-italian
authors:
  - name: Jane
    surname: Doe
    roles:
      - transcriber
      - project-manager
institutions:
  - name: Bibliothèque nationale de France
    roles:
      - digitization
description: a dataset created during the dh2023 htr-united workshop
project-name: htromance
language:
  - ita
production-software: eScriptorium + Kraken
automatically-aligned: false
script:
  - iso: Latn
script-type: only-manuscript
time:
  notBefore: '1500'
  notAfter: '1599'
hands:
  count: '1'
  precision: exact
license:
  - name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
format: Alto-XML
volume:
  - metric: files
    count: 10
transcription-guidelines: some transcription guidelines...
```
