### ISSUE TITLE
Adding dataset NaN

### ISSUE THREAD

**Issue by Lithos-Elaia** [HTR-United/htr-united#140]
Hello ! 

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
title: Oneirocriticon-Latinum
url: https://github.com/Lithos-Elaia/Oneirocriticon-Latinum
authors:
  - name: Pierre-Olivier
    surname: Beaulnes
    orcid: 0009-0009-2475-6017
    roles:
      - transcriber
      - project-manager
      - quality-control
institutions: []
description: >-
  Traitement des manuscrits contenant la traduction latin de l’Oneirocriticon du
  pseudo-Achmet.
language:
  - lat
production-software: eScriptorium + Kraken
automatically-aligned: false
script:
  - iso: Latn
script-type: only-manuscript
time:
  notBefore: '1176'
  notAfter: '1799'
hands:
  count: 1-per-file
  precision: estimated
license:
  name: CC-BY 4.0
  url: https://creativecommons.org/licenses/by/4.0/
format: Alto-XML
transcription-guidelines: SegmOnto
```
