### ISSUE TITLE
Adding dataset ARletta

### ISSUE THREAD

**Issue by lithlefranc** [HTR-United/htr-united#148]
Hello !

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
title: ARletta
url: zenodo.org/records/11191457
authors:
  - name: Lith
    surname: Lefranc
  - name: Ilja
    surname: Van Damme
  - name: Thibault
    surname: Clérice
  - name: Mike
    surname: Kestemont
institutions:
  - name: University of Antwerp
  - name: National Institute for Research in Digital Science and Technology, Paris
description: Open-source handwritten text recognition models for historic Dutch
project-name: Bias in History
project-website: https://www.bias-in-history.eu/
language:
  - nld
  - fra
production-software: eScriptorium + Kraken
automatically-aligned: false
script:
  - iso: Latn
script-type: only-manuscript
time:
  notBefore: '1600'
  notAfter: '1940'
hands:
  count: more-than-10
  precision: estimated
license:
  name: CC-BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/
format: Page-XML
volume:
  - metric: lines
    count: 431359
  - metric: regions
    count: 44536
  - metric: pages
    count: 10267
  - metric: characters
    count: 14253206
transcription-guidelines: diplomatic transcription: all of the text was transcribed verbatim, preserving all of its original features:
  - orthography: preserve original spelling
  - abbreviations: do not expand abbreviations
  - capitalization: retain original use of uppercase and lowercase letters
  - punctuation: transcribe punctuation marks exactly as they appear, even of they are unconventional by modern standards
  - special characters: include any special characters or symbols as they appear
  - formatting: maintain original formatting such as underlining or strikethrough
  - errors and corrections: include all errors and corrections found in the text
  - non-interpretative: avoid interpreting or modernizing the text
  - use the '@' symbol for characters you can not read an tag them as 'unclear' on baseline level
  - tag marginal text as 'marginalia' and main body text as 'paragraph' on region level
```
