### ISSUE TITLE
Adding dataset iForal

### ISSUE THREAD

**Issue by Arch-W** [HTR-United/htr-united#161]
Hello !

I would like to request the publication of the "iForal - Dataset," which contains a collection of Portuguese medieval manuscripts from the XIII, XIV, and XV centuries.

Thank you!

Here is our dataset YAML file: 
 ```yaml
authors:
- name: Alexandre
  orcid: 0009-0007-4781-3294
  roles:
  - aligner
  - quality-control
  surname: Matos
- name: Rui
  orcid: 0000-0001-5767-1583
  roles:
  - transcriber
  surname: Neves
- name: Gonçalo
  roles:
  - transcriber
  surname: Monteiro
- name: Catarina
  roles:
  - transcriber
  surname: Coelho
- name: Pedro
  orcid: 0009-0004-9005-6688
  roles:
  - aligner
  surname: Bastos
automatically-aligned: false
description: Ground Truth files for the iForal project.
format: Page-XML
hands:
  count: unknown
  precision: exact
institutions: []
language:
- lat
- por
license:
  name: CC-BY 4.0
  url: https://creativecommons.org/licenses/by/4.0/
production-software: eScriptorium + Kraken
project-name: iForal
project-website: https://iforal.hypotheses.org/
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
script:
- iso: Latn
script-type: only-manuscript
time:
  notAfter: '1491'
  notBefore: '1217'
title: iForal-Dataset
url: https://github.com/Arch-W/iForal-Dataset
volume:
- count: 776873
  metric: characters
- count: 180
  metric: files
- count: 8009
  metric: lines
- count: 183
  metric: regions
```
