### ISSUE TITLE
Documenter la provenance et les rôles

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united#17]
Dans le système actuel, tout est fait pour la réutilisation des données (ce qui est cool). Par contre, ça manque un peu de matière pour décrire des projets un peu plus complexe. J'aimerais bien avoir un truc du genre: 

```yaml
  - path: "./directory1"
    authors: 
      - name: Foo
        surname: Bar
        role: 
          - transcriber
          - aligner
      - name: Foo1
        surname: Bar2
        role: 
          - transcriber
    transcription-source: foo.bar.com # Optional
    digitization-source: gallica.com/arkl://///
    transcription-citation: "FOO BAR, foo.bar, 2021"
    volume:
     - Same system as the main here
  - path: "./directory2"
    authors: 
      - name: Foo
        surname: Bar
        role: 
          - transcriber
          - aligner
          - principal
      - name: Foo1
        surname: Bar2
        role: 
          - transcriber
    transcription-source: foo.bar.com # Optional
    digitization-source: gallica.com/arkl://///
    transcription-citation: "FOO BAR, foo.bar, 2021"
    volume:
     - Same system as the main here
```

Documentation:

- `path`: Dans le cas d'un dépôt, sous dossier ou chemin unix (donc acceptant les `**/*.xml`) permettant d'identifier une sous-partie
- `transcription-source`: Dans le cadre d'une transcription pré-existante, permet de documenter la source
- `transcription-citation`: Permet de citer. Peut-être à normaliser (genre APA ?)
- `digitization-source`: Source des documents images
- `volume`: même systême que pour le principal
- `authors`: Liste des auteurs-rices du dataset
  - `authors.name` et `authors.surname`: assez simple
  - `authors.roles`: 4 de possibles, non-exclusifs (sauf principal et support)
    - `transcriber`: a transcrit ou corrigé une transcription
    - `aligner`: a aligné un dataset déjà transcrit
    - `principal`: principal créateur-rice du dataset
    - `support`: personne support (aide au téléchargement, aide à la réflexion, tout ce qu'on veut)

Pour le dernier champ, on peut normaliser ça avec la regex `((?<name>[^,]+), (?<surname>[^,]+)\[(?<role>[^\]]+)\];)`: https://regex101.com/r/GIoocm/1

Si je ne dis pas de bêtise, en plus, on peut tout mapper facilement en DCT :)
