### ISSUE TITLE
Adding dataset - Chastel de joyeuse destinee

### ISSUE THREAD

**Issue by LaBretelle** [HTR-United/htr-united#179]
Hello, i want to propose a new dataset made by a student. 

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
title: Le Chastel de Joyeuse Destinée (Paris, Vérard, 1501)
url: https://github.com/LaBretelle/transcription-chastel
authors:
  - name: Yannis
    surname: PADOANELLO
    orcid: 0009-0008-6524-8089
    roles:
      - transcriber
      - aligner
      - quality-control
  - name: Paul
    surname: ROBERT
    orcid: 0000-0001-9619-5559
    roles:
      - support
institutions: []
description: >-
  Le Chastel de Joyeuse Destinée, long songe allégorique que seul le Jardin de
  Plaisance (Paris, Vérard, 1501) nous a conservé, n’avait encore jamais pu
  bénéficier d'une transcription complète. Ce projet de transcription s'inscrit
  dans l'édition du texte que le mémoire de master de Yannis PADOANELLO (Le
  motif de la prison dans le Jardin de Plaisance et fleur de rhetorique (1501)).
  L'exemplaire ayant servi à la transcription est le Rés. YE 168 de la BnF. Le
  texte est un imprimé.
project-name: >-
  Le motif de la prison dans le Jardin de Plaisance et fleur de rhétorique
  (1501)
language:
  - fra
production-software: eScriptorium + Kraken
automatically-aligned: false
script:
  - iso: Latn
script-type: only-typed
time:
  notBefore: '1501'
  notAfter: '1501'
hands:
  count: '1'
  precision: exact
license:
  name: CC-BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/
format: Alto-XML
sources:
  - reference: >-
      Vérard, A. V. (Éd.). (1501). Jardin de plaisance et fleur de rhétorique
      (Princeps) [Imprimée]. Vérard.
    link: https://catalogue.bnf.fr/ark:/12148/cb13164222t
volume:
  - metric: pages
    count: 60
  - metric: lines
    count: 60
  - metric: files
    count: 60
transcription-guidelines: >-
  Le document a été transcrit de façon diplomatique (aucune correction des
  erreurs, pas de résolution des abréviations, ni de modernisation). Toutefois,
  le ſ (s long) a systématiquement été remplacé par une s. Les lettrines
  constituent, dans notre transcription, une ligne à part entière.
```
