### ISSUE TITLE
Adding dataset

### ISSUE THREAD

**Issue by buccacoronatus** [HTR-United/htr-united#183]
Hello ! [Complete your message here]

Here is our dataset YAML file: 
 ```yaml
schema: https://htr-united.github.io/schema/2023-06-27/schema.json
title: >-
  Ground Truth Set for Handwritten Text Recognition (HTR/OCR): Dresdner
  Hofdiarium 1653-56 (Mscr.Dresd.K.113) - 17th century Kurrent manuscript
url: https://doi.org/10.5281/zenodo.15303398
authors:
  - name: Stefan
    surname: Beckert
    orcid: 0009-0005-2394-0075
    roles:
      - transcriber
      - aligner
      - project-manager
      - quality-control
institutions: []
description: >-
  Twelve pages of Ground Truth from the "Hofdiarium des Kurfürsten Johann Georgs
  II. 1653-1656" (SLUB Mscr.Dresd.K113;
  https://www.wikidata.org/wiki/Q133883726). The handwriting is a typical late
  17th century Saxon kurrent ("Kanzleikurrent"), with occasional words written
  in bastarda or fraktur-like script.


  This transcription is part of a larger project regarding the Dresden court
  diaries. Check https://slub-dresden.academia.edu/StefanBeckert for further
  updates.
project-website: https://slub-dresden.academia.edu/StefanBeckert
language:
  - deu
production-software: eScriptorium + Kraken
automatically-aligned: false
script:
  - iso: Latn
script-type: only-manuscript
time:
  notBefore: '1653'
  notAfter: '1656'
hands:
  count: '1'
  precision: exact
license:
  name: CC-BY 4.0
  url: https://creativecommons.org/licenses/by/4.0/
format: Alto-XML
volume:
  - metric: pages
    count: 12
transcription-guidelines: >-
  Transcription guidelines are oriented on the DTABF-M schema
  (https://www.deutschestextarchiv.de/doku/basisformat/manuskript.html), but
  have been adapted as follows:


  - I and J majuscules are not distinguished

  - u and v are reproduced true to the original (e.g. vnd)

  - Long-s (ſ) and round-s (s) are distinguished

  - sz ligature is rendered as ß in Kurrent scripts and as sz (e.g. "Libusza")
  in Antiqua scripts

  - ij ligature is rendered as y

  - other ligatures, if they occur at all, are dissolved

  - r graphemes are rendered as r in their modern day form

  - an m with a nasal stroke was rendered as a simple mm

  - Where possible, abbreviation signs (Abbrechungszeichen) for the contemporary
  identification of abbreviations have been included as single letters and not
  marked separately. The subsequent punctuation mark (“.” or “:”) for further
  identification of the abbreviation has also been included (cf. also Capelli,
  1928, Lexicon abbreviaturarum I, p.X) 

  - Diacritics in u were not marked

  - In the case of uncertain capitalization, an approximation is sought via the
  letter size
```
