### ISSUE TITLE
New repo for GenAuto TD Corpus

### ISSUE THREAD

**Issue by jpmjpmjpm** [HTR-United/htr-united#23]
You can now reference [GenAuto TD Corpus](https://github.com/jpmjpmjpm/genauto-td-htr.git) that was created.

The associated [htr-united.yml](https://github.com/jpmjpmjpm/genauto-td-htr/blob/128fc18fe324e9b0f1a7564213a7a37198733265/htr-united.yml) file content is:

```
title : 'GenAuto TD Corpus'
url: 'https://github.com/jpmjpmjpm/genauto-td-htr.git'
project-name: 'GenAuto'
project-website: ''
authors:
    - name: 'Boutet'
      surname: 'Jean-François'
      roles:
      - 'transcriber'
      - 'aligner'
    - name: 'Merx'
      surname: 'Jean-Pierre'
      roles:
      - 'transcriber'
      - 'aligner'
      - 'project-manager'
description: '150 transcribed images from "Tables Décennales" French Civil Registry.
Those come from Sermaises and Romilly-sur-Seine municipalities. '
language: 'French'
#other-languages:
#    - "Optional"
script: 'Latin'
script-type: 'only-manuscript'
time: 1792--1902
hands:
    - count: 'less-than-11'
      precision: 'estimated'
license:
    - {name: 'CC-BY 4.0', url: 'https://creativecommons.org/licenses/by/4.0/'}
format: 'Alto-XML'
volume:
    - {count: "300", metric: "pages"}
    - {count: "150, metric: "images"}

```
