### ISSUE TITLE
New repo Scripta/BiblIA

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#26]
Build description for https://zenodo.org/record/5167263#.YT4wUH0682y (BiblIA) (after request from Daniel Stoekl)

**Comment by alix-tz** [comment]
There are parts of the description that can't be filled from just the description on Zenodo.

- `dates`
- `hands`
- `roles`

```
title : 'BiblIA'
url: 'https://zenodo.org/record/5167263'
project-name: 'Scripta'
project-website: 'https://escripta.hypotheses.org/'
authors:
    - name: 'Stökl Ben Ezra'
      surname: 'Daniel'
      roles:
      - 'project-manager'
    - name: 'Brown-DeVost'
      surname: 'Bronson'
    - name: 'Jablonski'
      surname: 'Pawel'
    - name: 'Kiessling'
      surname: 'Benjamin'
    - name: 'Lolli'
      surname: 'Elena'
    - name: 'Lapin'
      surname: 'Hayim'
description: 'This dataset for Handwritten Text Recognition includes layout segmentation (regions, toplines and linepolygons) and unicode-transcriptions in alto 4.2 XML for 202 images of Medieval Hebrew manuscripts from the Bibliothèque nationale de France (BnF, National Library of France) and the Biblioteca Apostolica Vaticana (BAV, Vatican Library) corresponding to the article "BiblIA - a General Model for Medieval Hebrew Manuscripts and an Open Annotated Dataset" by Daniel Stökl Ben Ezra, Bronson Brown-DeVost, Pawel Jablonski, Benjamin Kiessling, Elena Lolli, and Hayim Lapin, published in HIP@ICDAR 2021 held in Lausanne, September 2021.'
language: 'medieval hebrew'
script: 'Hebrew'
script-type: 'only-manuscript'
time: 0000--0000
hands: 
    - count: '1'
      precision: 'exact'
license:
    - {name: 'CC-BY-NC-SA 4.0', url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/'}
format: 'Alto-XML'
volume:
    - {count: "202", metric: "pages"}
```
