### ISSUE TITLE
Repo template shouldn't appear in the catalog

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#54]
We need to make sure HTRUC doesn't parse it

https://github.com/HTR-United/htr-united/blob/32c7fa04bdcb33e088519f1cee4268bfb42e0ea0/htr-united.yml#L1134

```
- schema: https://htr-united.github.io/schema/2021-10-15/schema.json
  title: "Repository\u2019s Title"
  url: Link to your data repository
  project-name: 'Your project name
    '
  project-website: Link to your project
  authors:
  - name: Author Name
    surname: Author Firstname
    roles:
    - transcriber
  description: "Description \n"
  language:
  - eng
  - fra
  script:
  - Latn
  script-type: only-manuscript
  time:
    notBefore: '1500'
    notAfter: '1300'
  hands:
    count: 1-per-folder
    precision: exact
  license:
  - name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  format: Alto-XML
  volume:
  - metric: files
    count: 10
```
